name: react-app
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v6
      - name: setup node version 20
        uses: actions/setup-node@v6
        with:
            node-version: 20

      - name: Adding Cache
        uses: actions/cache@v4
        id: npm-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: install npm package
        run: npm ci

      - name: run test
        run: npm run test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: checking out the repo
        uses: actions/checkout@v6
      - name: setup node version 20
        uses: actions/setup-node@v6
        with:
             node-version: 20
      - name: Adding Cache
        uses: actions/cache@v4
        id: npm-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          
      - name: install npm package
        run: npm ci

      - name: build project
        run: npm run build
      - name: Uploading the artifact
        uses: actions/upload-artifact@v7
        with:
          name: dist-file
          path: dist
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Downloading the artifact
        uses: actions/download-artifact@v8
        with:
          name: dist-file
          path: dist
      - name: Deploy
        run: echo "Deployment successful!"
        
